### PR TITLE
Tried to address issue #6

### PR DESCRIPTION
**Pull request by hc8756**
Hi @ender-titan1 ! I'm interested in contributing to this project. I tried to do all things mentioned in the issue. Ideally, I would have been able to run the project on Unity to check if it worked, but I was having file path issues.  Hope this helps.

### CODE REVIEW

**Comment by ender-titan1** [comment]
Hello, @hc8756, I really didn't expect anyone to contribute at this stage. I was about to make a video on my youtube about the project and I was just prepping this repo for the vid. Well, I appreciate your help. The files are quite old so they require some cleaning (that is why they are such a mess). I will need to upload more files so that the build passes, so don't worry about that if you are going to contribute more. One note: next time you open a PR please write "closes #issue" so it is easier to navigate. Again, thanks for the help.

**Review by ender-titan1 — COMMENTED** [review]
Good work, but for some reason, probably just an error in upload some scripts ended up in the "animation" folder, I will move those to the scripts folder so you can edit them (there are only like 4 quite small files)

**Comment by ender-titan1** [comment]
you will have to move your edits to the .cs scripts in the scripts folder. (just copy and paste)

**Comment by hc8756** [comment]
Hello- thanks for getting back to me- I will try to stick to the proper pr naming convention in any future contributions. Although some of the cs files ended up in the animation folder (sorry about that), I have already gone through them and made all the variables lower case. So I don't think there's anything left for me to do once you move them.

**Comment by ender-titan1** [comment]
Oops, well I messed up, this is my first _real_ repo so I don't really know how to move files (could have just looked it up but whatever), I have deleted and reuploaded those files. No worries I can finish up this PR since it's my mistake.

**Pull request merged**
