### PR TITLE
PR for Issue #25

### LINKED ISSUE #25: Add comments and summaries to the code.
Ex.
```
//<summary>
// gives the player infinite health
//</summary>
public void SetInvincibility(bool value)
{
        Invincibility = value;
        character_variables VariableManager;

        //gets the character_variables script
        VariableManager = player.GetComponent<character_variables>();
        if(value == true)
        {
            VariableManager.StoredHealth = VariableManager.health;
        }
        else
        {
            VariableManager.health = VariableManager.StoredHealth;
            VariableManager.StoredHealth = 0;
        }
            
}
```

### PR DESCRIPTION
**Pull request by hc8756**
closes #25 

@ender-titan1 I went through the scripts in the scripts folder and commented on all the functions that I understood. It was a little difficult as I can't run a lot of the scenes due to null reference exceptions, so apologies if I got anything wrong.

### CODE REVIEW

**Comment by ender-titan1** [comment]
> null reference exceptions
Hmm, I copied and ran this repo without problems on my machine, ill try it again on a different machine.

**Review by ender-titan1 — CHANGES_REQUESTED** [review]
start.cs line 10 has a typo
player_respawn.cs line 40 should be changed to: "sets variables for respawn" since `player_interactivity.cs` handles death.

But other than that looks good!

**Comment by hc8756** [comment]
Hi! I made the requested changes but for some reason it fails a check even though there are no conflicts with the base branch. I can't imagine why considering I'm just commenting...

**Comment by ender-titan1** [comment]
yeah, i know error  `MSB1011: Specify which project or solution file to use because this folder contains more than one project or solution file.` is a problem but I managed to build it on my machine. But if you know how to fix it comment here.

**Review by ender-titan1 — APPROVED** [review]
Looks good!

**Pull request merged**
